In [1]:
import numpy as np
import scipy.linalg as sp_linalg

In [2]:
A= [[1,  2,  3],
    [2, -4,  6],
    [3, -9, -3]]
A= np.array(A)
A

array([[ 1,  2,  3],
       [ 2, -4,  6],
       [ 3, -9, -3]])

In [3]:
P,L,U= sp_linalg.lu(A)
P, L, U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.33333333, 1.        , 0.        ],
        [0.66666667, 0.4       , 1.        ]]),
 array([[ 3. , -9. , -3. ],
        [ 0. ,  5. ,  4. ],
        [ 0. ,  0. ,  6.4]]))

In [4]:
# 驗算
P@L@U

array([[ 1.,  2.,  3.],
       [ 2., -4.,  6.],
       [ 3., -9., -3.]])

In [5]:
assert (A==P@L@U).all()

In [6]:
assert np.allclose(A, P@L@U)